<a href="https://colab.research.google.com/github/yeanni-w0n/essa0308_yw_01/blob/main/3_8_%E1%84%89%E1%85%A6%E1%84%89%E1%85%A7%E1%86%AB_%E1%84%86%E1%85%AE%E1%86%AB%E1%84%8C%E1%85%A6_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy Version:", np.__version__)
print(np.show_config())

NumPy Version: 1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros 

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
V = np.zeros(10)
print(V)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
V = np.zeros((10,10))
print("%d bytes" % (V.size * V.itemsize))

800 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
V = np.arange(10,50)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
V = np.arange(21)
V = V[::-1]
print(V)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array1 = np.arange(9)
matrix1 = array1.reshape((3, 3))
print(matrix1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
nze=np.nonzero([1,2,0,0,4,0])
print(nze)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
#항등행렬 만들기
im = np.eye(3)
print(im)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
r=np.random.random((3, 3, 3))
print(r)


[[[9.28117660e-01 9.48438537e-01 4.19129749e-01]
  [6.08144201e-01 7.06088943e-01 8.61526168e-04]
  [2.04854306e-01 5.19626193e-01 3.34542059e-01]]

 [[6.61442896e-01 9.53840674e-01 3.15331963e-01]
  [1.27382374e-01 6.27102170e-02 3.19660047e-01]
  [4.74624489e-01 3.80781691e-01 3.90358183e-01]]

 [[8.72728729e-01 1.66983817e-01 6.63877220e-01]
  [1.36545826e-01 8.13250982e-01 6.23100095e-01]
  [1.74938318e-01 7.68919217e-01 2.04988369e-01]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
rv = np.random.random((10,10))
rvmin, rvmax = rv.min(), rv.max()
print(rvmin, rvmax)

0.004811916075575962 0.9993061898361079


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
rv = np.random.random(30)
m = rv.mean()
print(m)

0.5097577002439004


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix3 = np.diag([1, 2, 3, 4], k=-1)
print(matrix3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.50461507 -0.68072507  0.860363   -0.85349417  0.68915981]
 [ 1.213395   -0.59023564  0.75469229  1.31800858 -0.81803359]
 [-1.10972735 -1.13932051  1.37510562 -1.7628707  -0.11233636]
 [ 0.59906392 -0.94212974 -0.93596226  0.31202996 -0.36124458]
 [ 0.46306077  1.29451432  1.08532853 -1.58873572  1.43470897]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
dtype = np.dtype([("R", np.ubyte),
                  ("G", np.ubyte),
                  ("B", np.ubyte),
                  ("A", np.ubyte)])
print(dtype)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
M = np.ones((5,3)) @ np.ones((3,2))
print(M)

#5행2열을 갖는것까지 이해가 가는데 왜 3으로 나오는지 질문

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
e = np.arange(12)
e[(3 < e) & (e < 8)] *= -1
print(e)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

마지막이 옳지 않다. 왜냐하면 Z의 각 원소가 자신과 비교하여 원소별 곱셈의 결과보다 작은지 여부를 확인하고 싶다면 괄호를 사용하여 명확히 하기 때문이다.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-49-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-49-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-49-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])